### ISSUE TITLE
vendor.js file is missing

### ISSUE THREAD

**Issue by kvidek** [degordian/generator-degordian-phprontend#1]
It would be great if vendor.js file with default imports (jQuery, svgxuse, TweenMax...) could be created inside static/js/ with Yoman generator
EDIT: Also some other files were not created (HomePage.js with it's content). I see that files exist inside Yoman template (static folder) but they were not created during project generation so we should test this again (yii project boilerplate was selected).

**Comment by renatoruk** [comment]
Which version are you using?

You can check that with: `npm list -g generator-degordian-phprontend`

**Comment by renatoruk** [comment]
Closing this as it was an earlier version of the generator without `vendor.js`.
