### ISSUE TITLE
IE11 babel problem

### ISSUE THREAD

**Issue by igorbumba** [degordian/generator-degordian-phprontend#2]
Install:
`npm install --save babel-polyfill`

Add this line of code at the end of `vendor.js`:
`import  @'babel-polyfill';`

**Comment by renatoruk** [comment]
Fixed in d0f7c48c64a74a4cd443b94a01f02153d3f69374 (at least for now until babel 7 becomes stable or we configure the transforms and polyfills manually), please update the module locally.
